name: changelog-generate

on:
  push:
    tags:
    - '*'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0' # get tags
          ref: 'master'

      - name: run-script
        shell: bash
        run: $GITHUB_WORKSPACE/create_changelog.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update changelog
